### ISSUE TITLE
Please add licensing information

### ISSUE THREAD

**Issue by ssokolow** [pgooch/jQueryLinenNumbersPlugin#1]
This plugin looks perfect for my uses, but I can't find any license information anywhere.

According to the law in countries like the U.S. and Canada which are signatories to the Berne Convention, that means tha "all rights reserved" copyright applies (by default) and I'm not allowed to use your plugin in my programs.

GitHub set up this site to help you choose and add a license:
http://choosealicense.com/

**Comment by HasPhillip** [comment]
This can be considered to be under the GNU General Public License v3.0, I will update the readme to reflect this later today.

**Comment by ghost** [comment]
That is not enough. I added **LICENSE.md** to anyone may read it and sent **Pull request**

**Comment by pgooch** [comment]
Added.
