### ISSUE TITLE
Please make "example.html" viewable without downloading the repo

### ISSUE THREAD

**Issue by ssokolow** [pgooch/jQueryLinenNumbersPlugin#2]
Currently, I can't see any easy way to view `example.html` without downloading the file.

If you rename it to `index.html`, [rename the branch](https://gist.github.com/lttlrck/9628955) from `master` to `gh-pages`, and then set `gh-pages` as the default branch in your repository settings, then you can use the same branch for both the project page and https://pgooch.github.io/jQueryLinenNumbersPlugin

**Comment by HasPhillip** [comment]
I may change update this in the future, but at this time the project has some issues and seems to no longer work. I never sued it for anything and it was not extensively tested. 

If you would like to see a preview of this, or any other project without the appropriate HTML preview you can use htmlpreview.github.io to get a preview like this: https://htmlpreview.github.io/?https://github.com/pgooch/jQueryLinenNumbersPlugin/blob/master/example.html

**Comment by ssokolow** [comment]
Aside from a bug I managed to trigger where the last line was left un-numbered, it seemed to work perfectly in my Firefox when I tested it.

**Comment by drakonoved** [comment]
[Check here](https://drakonoved.github.io/line-numbers/)

**Comment by pgooch** [comment]
Fixed and updated. Thanks drakonoved.
